---
title: "THTuan6"
author: "LeTienManh_23001535"
date: "2024-03-14"
output:
  html_document: default
  word_document: default
---
1.A
```{r}
x = c(48, 49, 51, 52, 49, 41, 40, 38, 35, 40, 43)
day = 5
mean(x[day:(day+4)])
print("lay gt trung binh tu day den day+4")
x[1:5]
print("x[1] den x[5]")
x[(length(x)-5):length(x)]
print("lay 5 gtri cuoi")
sum( x > 50)
print("dem nhung gtri x >50")
sum(x[x>50])
print("sum nhung gia tri x>50")
sum(x>50 | x < 40)
("dem nhung gia tri >50 hoac <40")

```
1.B
```{r}
time <- c(17, 16, 10, 24, 22, 15, 21, 7, 17, 22)
min(time)
mean(time)
max(time)
#b
time[time == 22] = 5
time
#c
y <- c(20, 5 , 26, 16, 23, 25)
z = c(time,y)
z
sum(z>21)/length(z)


```
Bai2
```{r}
set.seed(217)
data <- read.csv("D:\\Datasets\\dulieu2.csv")
dim(data)
a <- length(data[,1])
#b <- length(row.names(data))

row <- sample(a,a*80/100,replace = F)
data1 <- data[row,]
dim(data1)
#data1
data2 <- data[-row,]
dim(data2)
#data2
#c
gr1 = mean(data1$Gross.Sales)
gr2 = mean(data2$Gross.Sales)

if(gr1 > gr2){
  print("Gr1 ban nhieu hon gr2")
} else print("gr2 ban nhieu hon gr1")

#d
data$Assessment = abs(10*data$Units.Sold- 7/(10*10)*data$Sale.Price+5*data$Discounts-data$Sales)
data$Assessment
#e
#t1 <- sample(a,a/2,replace = F)
t1 <- nrow(data)
a = sample(t1,t1/2,replace = F)
tran1 <- data[a,]
tran2 <- data[-a,]
b = sample(350,175,replace = F)
train1 <- tran2[b,]
train2 <- tran2[-b,]
train3 <- tran1[b,]
train4 <- tran1[-b,]
#f
customService <- function(x){
  m = mean(x$Assessment)
  #print(m)
  s = subset(x,x$Assessment > m)
  #print(s)
  f = nrow(s)/length(x$Assessment)
  #print(f)
  p = 2/3
  n = length(x$Assessment)
  #print(n)
  t = abs((f-p)*sqrt(n)/(p*(1-p)))
  if (t > 1.96) print("dc cua no day :>")
}

res1 = customService(train1)
res2 = customService(train2)
res3 = customService(train3)
res4 = customService(train4)

# m = mean(data$Assessment)
# m
# s = subset(data,data$Assessment > m) 
# nrow(s)
# length(data$Assessment)
```
Bai3
```{r}
x <- c(1,5,1,-1)
A <- matrix(x,nrow=2)
A
y <- c(7,-3,3,7)
B <- matrix(y,nrow = 2)
B
z <- c(1,0,0,1)
E <- matrix(z,nrow = 2)
C <- solve(A)%*%(B-E)
C
```

Bai4 
```{r}
time <- c(17, 16, 20, 24, 22, 15, 21, 15, 17, 22)
m <- mean(time)
a <- c(22, 23, 18, 25, 20)
time1 <- c(time,a)
m1 <- mean(time1)
if  (m <= m1 ) {print(paste0("Thời gian đi làm trung bình mới nhiều hơn ban đầu ",m1-m," second")) } else { print(paste0("Thời gian đi làm trung bình mới ít hơn ban đầu ",m-m1," second"))}

```
Bai5
```{r}
#a
 dl <- read.csv("D:\\Datasets\\14-3.csv")
 colSums(is.na(dl))
dtpro <- function(n,field){
  v <- field[-n]
  #print(v)
  field[n] <- sample(field,1,replace = T)
}
  for (i in names(dl)){
    #print(i)
    c <- which(is.na(dl[[i]]))
    dl[[i]][c] = dtpro(c,dl[[i]])

  }

 colSums(is.na(dl))
 #b
 a <- max(dl$UnitPrice)
 a
 #c
 carrot <- subset(dl,dl$Product == "Carrot")
#carrot
 b <- sum(carrot$Quantity)
 b
#d
product <- c(table((dl$Product)))
product
#e
dl$City[which.max(dl$TotalPrice)]
cookies <- subset(dl,dl$Product == "Cookies")
cookies$City[which.max(cookies$TotalPrice)]
#f
dl$TotalPrice <- dl$Quantity * dl$UnitPrice

```
Bai6

```{r}
#a
wine <- read.csv("D:\\Datasets\\winequality.csv")

winepro <- function(pos,field){
  field[pos] = mean(field, na.rm = T)
}

for (i in names(wine)){
  c <- which(is.na(wine[[i]]))
  if ( length(c) > 0 ){
    wine[[i]][c] = winepro(c,winepro[[i]])
  }
  
  
  
}
colSums(is.na(wine))
#b
wine5 <- mean(wine$pH[wine$quality ==5])
wine5
wine6 <- mean(wine$pH[wine$quality == 6])
wine6
if ( wine5 >= wine6) {
  print("pH wine quality 5 > wine quality 6 ")
  
} else {
  print(" pH wine quality 6 > wine quality 5")
}
#c 
wine$citric.acid <- replace(wine$citric.acid,wine$citric.acid == 0,0.01)
#wine$citric.acid
#d
evaluate <- function(alcohol, quality,pH){
  k =(alcohol*quality)/pH
  print(k)
  if(k > 7.5) print("Good")
  else print ("Bad")
}
a <- wine[wine$citric.acid == 0.01 & wine$chlorides == 0.076 & wine$fixed.acidity == 7.4,]
a <- unique(a)
evaluate(a$alcohol,a$quality,a$pH)

```
bai7 
```{r}
x <-c(170,180,190,200,210,220,230)
r <-c(30,40,55,75,85,50,35)
m=0
for(i in length(x)){
  if(x[i]>200){
    m = m +r[i]
  }
}
t = (m/sum(r)-1/3)*sqrt(sum(r))/(2/9)
t
if (t>1.96) {
  print("suy doan dung")
} else {
  print("suy doan sai")
}  
```
bai 8 
```{r}
data <- read.csv("D:\\Datasets\\Product.csv")
#g
colSums(is.na(data))
dtpro <- function(pos,field){
  vt <- field[-pos]
  field[pos] <- sample(vt,length(pos),replace = T)
}
for (i in names(data)){
  c <- which(is.na(data[[i]]))
  if (length(c)>0){
    data[[i]][c] = dtpro(c,data[[i]])
  }
}
#data
colSums(is.na(data))
#h
length(data[,1])
```